version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: nest-api
    ports:
      - "5433:5432"  # Changed host port to 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
  test-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: nest-api
    ports:
      - "5434:5432"  # Changed host port to 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    

volumes:
  postgres_data:
